# ASSIGNMENT OBSERVATIONS & NOTES

In [263]:
"""
IRIS & IONOSPHERE DATASET:

-    Implemented the K Nearest Neighbours algorithm for a general K but used 1 & 3 instead of K in the programs.

-    Normalization can be used to rescale the data in the range of 0 to 1. I have commented the codes in 7th CELL.
It ll be used for test datset n we can find the values similarly.

-    We can evaluate the program by using K-Fold Validation.

-    Plots can be used to generate the graphical reprentation.

-    Genralized k value we can use the below commented function by adding the 2 lines which will ask for an iput integer value of k in KNN:
Added as a comment line in my program
# k=int(input("enter the k value of KNN"))
# y_pred_data = KNN_Neighbors(new_train_data, new_test_data, k)

-   

"""



'\nIRIS & IONOSPHERE DATASET:\n\n- Implemented the K Nearest Neighbours algorithm for a general K but used 1 & 3 instead of K in the programs.\n\n- Normalization can be used to rescale the data in the range of 0 to 1. I have commented the codes in 7th CELL.\nIt ll be used for test datset n we can find the values similarly.\n\n- We can evaluate the program by using K-Fold Validation.\n\n- Plots can be used to generate the graphical reprentation.\n\n- Genralized k value we can use the below commented function by adding the 2 lines which will ask for an iput integer value of k in KNN:\nAdded as a comment line in my program\n# k=int(input("enter the k value of KNN"))\n# y_pred_data = KNN_Neighbors(new_train_data, new_test_data, k)\n\n'

# KNN ALgorithm for IRIS_DATASET(General K value(Commented) & 1-NN


In [264]:

from random import seed
from random import randrange
from csv import reader
from math import sqrt
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
import numpy as np
iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [265]:
iris["data"], iris['target']

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [268]:
#Split the Dataset using DOB as random_state
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris['data'], iris['target'], random_state=705)

In [269]:
print(len(X_train), len(X_test), len(y_train), len(y_test))

y_test

112 38 112 38


array([1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 0, 2, 1, 1, 2, 1, 1,
       1, 0, 0, 0, 1, 2, 0, 2, 2, 0, 2, 2, 1, 1, 0, 1])

In [270]:
new_train_data = []
for i in range(len(X_train)):
    print(X_train[i])
    print(y_train[i])
    new_train_data.append(np.append(X_train[i], y_train[i]).tolist())
    print(new_train_data)

[5.5 2.3 4.  1.3]
1
[[5.5, 2.3, 4.0, 1.3, 1.0]]
[5.  3.4 1.6 0.4]
0
[[5.5, 2.3, 4.0, 1.3, 1.0], [5.0, 3.4, 1.6, 0.4, 0.0]]
[4.4 3.2 1.3 0.2]
0
[[5.5, 2.3, 4.0, 1.3, 1.0], [5.0, 3.4, 1.6, 0.4, 0.0], [4.4, 3.2, 1.3, 0.2, 0.0]]
[5.6 2.7 4.2 1.3]
1
[[5.5, 2.3, 4.0, 1.3, 1.0], [5.0, 3.4, 1.6, 0.4, 0.0], [4.4, 3.2, 1.3, 0.2, 0.0], [5.6, 2.7, 4.2, 1.3, 1.0]]
[5.7 2.6 3.5 1. ]
1
[[5.5, 2.3, 4.0, 1.3, 1.0], [5.0, 3.4, 1.6, 0.4, 0.0], [4.4, 3.2, 1.3, 0.2, 0.0], [5.6, 2.7, 4.2, 1.3, 1.0], [5.7, 2.6, 3.5, 1.0, 1.0]]
[5.4 3.4 1.5 0.4]
0
[[5.5, 2.3, 4.0, 1.3, 1.0], [5.0, 3.4, 1.6, 0.4, 0.0], [4.4, 3.2, 1.3, 0.2, 0.0], [5.6, 2.7, 4.2, 1.3, 1.0], [5.7, 2.6, 3.5, 1.0, 1.0], [5.4, 3.4, 1.5, 0.4, 0.0]]
[5.2 4.1 1.5 0.1]
0
[[5.5, 2.3, 4.0, 1.3, 1.0], [5.0, 3.4, 1.6, 0.4, 0.0], [4.4, 3.2, 1.3, 0.2, 0.0], [5.6, 2.7, 4.2, 1.3, 1.0], [5.7, 2.6, 3.5, 1.0, 1.0], [5.4, 3.4, 1.5, 0.4, 0.0], [5.2, 4.1, 1.5, 0.1, 0.0]]
[7.4 2.8 6.1 1.9]
2
[[5.5, 2.3, 4.0, 1.3, 1.0], [5.0, 3.4, 1.6, 0.4, 0.0], [4.4, 3.2, 1.3, 0.2, 0

In [271]:
new_test_data = []
for i in range(len(X_test)):
    new_test_data.append(np.append(X_test[i], y_test[i]).tolist())
    print(X_test[i])
    print(y_test[i])
    print(new_test_data)
    

[6.  2.7 5.1 1.6]
1
[[6.0, 2.7, 5.1, 1.6, 1.0]]
[5.9 3.2 4.8 1.8]
1
[[6.0, 2.7, 5.1, 1.6, 1.0], [5.9, 3.2, 4.8, 1.8, 1.0]]
[5.  3.5 1.6 0.6]
0
[[6.0, 2.7, 5.1, 1.6, 1.0], [5.9, 3.2, 4.8, 1.8, 1.0], [5.0, 3.5, 1.6, 0.6, 0.0]]
[5.1 3.8 1.9 0.4]
0
[[6.0, 2.7, 5.1, 1.6, 1.0], [5.9, 3.2, 4.8, 1.8, 1.0], [5.0, 3.5, 1.6, 0.6, 0.0], [5.1, 3.8, 1.9, 0.4, 0.0]]
[5.7 4.4 1.5 0.4]
0
[[6.0, 2.7, 5.1, 1.6, 1.0], [5.9, 3.2, 4.8, 1.8, 1.0], [5.0, 3.5, 1.6, 0.6, 0.0], [5.1, 3.8, 1.9, 0.4, 0.0], [5.7, 4.4, 1.5, 0.4, 0.0]]
[4.4 3.  1.3 0.2]
0
[[6.0, 2.7, 5.1, 1.6, 1.0], [5.9, 3.2, 4.8, 1.8, 1.0], [5.0, 3.5, 1.6, 0.6, 0.0], [5.1, 3.8, 1.9, 0.4, 0.0], [5.7, 4.4, 1.5, 0.4, 0.0], [4.4, 3.0, 1.3, 0.2, 0.0]]
[4.6 3.2 1.4 0.2]
0
[[6.0, 2.7, 5.1, 1.6, 1.0], [5.9, 3.2, 4.8, 1.8, 1.0], [5.0, 3.5, 1.6, 0.6, 0.0], [5.1, 3.8, 1.9, 0.4, 0.0], [5.7, 4.4, 1.5, 0.4, 0.0], [4.4, 3.0, 1.3, 0.2, 0.0], [4.6, 3.2, 1.4, 0.2, 0.0]]
[5.4 3.9 1.7 0.4]
0
[[6.0, 2.7, 5.1, 1.6, 1.0], [5.9, 3.2, 4.8, 1.8, 1.0], [5.0, 3.5, 1.6, 0.6, 0

In [272]:
 # Rescaling & finding the max n minimum value:
# def iris_mnmx(dataset):
#     mxmn = list()
#     for i in range(len(dataset[0])):
#         col_values = [row[i] for row in dataset]
#         value_min = min(col_values)
#         value_max = max(col_values)
#         mxmn.append([value_min, value_max])
#     return mxmn
 
# # Rescale dataset columns to the range 0-1
# def normalize_dataset(dataset, mxmn):
#     for row in dataset:
#         for i in range(len(row)):
#             row[i] = (row[i] - mxmn[i][0]) / (mxmn[i][1] - mxmn[i][0])
       


# normalize_dataset(new_train_data,iris_mnmx(new_train_data))
# print(new_train_data)

In [273]:
print(len(new_test_data),len(new_train_data))

38 112


In [274]:
#Normalization is not used but can be implemented if required
#Used merge sort for sorting the distances & correspondig dataset
def mergeSort(nlist):
    #print("Splitting ",nlist)
    if len(nlist)>1:
        mid = len(nlist)//2
        lefthalf = nlist[:mid]
        righthalf = nlist[mid:]

        mergeSort(lefthalf)
        mergeSort(righthalf)
        i=j=k=0       
        while i < len(lefthalf) and j < len(righthalf):
            if lefthalf[i][1] < righthalf[j][1]:
                nlist[k]=lefthalf[i]
                i=i+1
            else:
                nlist[k]=righthalf[j]
                j=j+1
            k=k+1

        while i < len(lefthalf):
            nlist[k]=lefthalf[i]
            i=i+1
            k=k+1

        while j < len(righthalf):
            nlist[k]=righthalf[j]
            j=j+1
            k=k+1
            
        
#Finding the Euclidean distanct datapoints/vectors
def distance_Eucl(point1, point2):
    distance = 0.0
    for i in range(len(point1)-1):
        distance =distance + ((point1[i] - point2[i])**2)
    return sqrt(distance)
 
# Find neighbours
def neighbours_search(train_data, rows_test, knn_neighbours):
    distances = list()
    for rows_train in train_data:
        dist = distance_Eucl(rows_test, rows_train)
        distances.append((rows_train, dist))
    mergeSort(distances)    
    neighbors = list()
    for i in range(knn_neighbours):
        neighbors.append(distances[i][0])
    return neighbors
 
# Doing prediction with the neighbours
def classification_pred(train_data, rows_test, knn_neighbours):
    neighbors = neighbours_search(train_data, rows_test, knn_neighbours)
    op_val = [line[-1] for line in neighbors]
    prediction_val = max(set(op_val), key=op_val.count)
    return prediction_val
 
# KNN Algorithm
def KNN_Neighbors(train_data, test, knn_neighbours):
    preds = list()
    for row in test:
        output = classification_pred(train_data, row, knn_neighbours)
        preds.append(output)
#         print(predictions)
    return(preds)


            

In [276]:
#for genralized k value we can use the below commented function:


# k=int(input("enter the k value of KNN"))
# y_pred_data = KNN_Neighbors(new_train_data, new_test_data, k)

y_pred_data = KNN_Neighbors(new_train_data, new_test_data, 1)
y_pred = []

y_pred = y_pred_data
np.array(y_pred), y_test

# print(len(y_pred) , len(y_test))
# print(y_pred , y_test)
count=0
for i in range(len(y_pred)):
    if y_pred[i]==y_test[i]:
        count=count+1
# print(count)
Acc=count/len(y_pred)
print("Accuracy is :", Acc)
Err_Rate= 1-Acc
print("Error Rate is :",Err_Rate)

Accuracy is : 0.9210526315789473
Error Rate is : 0.07894736842105265


# IRIS_Dataset & 3-NN Algorithm

In [277]:
"""
Implemented the K Nearest Neighbours algorithm for a general K but used 1 & 3 instead of K in the programs
 
"""


from random import seed
from random import randrange
from csv import reader
from math import sqrt
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
import numpy as np
iris = load_iris()
iris.keys()


dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [278]:
iris["data"], iris['target']

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [279]:
#Split the Dataset using DOB as random_state
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris['data'], iris['target'], random_state=705)

In [280]:
print(len(X_train), len(X_test), len(y_train), len(y_test))

y_test

112 38 112 38


array([1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 0, 2, 1, 1, 2, 1, 1,
       1, 0, 0, 0, 1, 2, 0, 2, 2, 0, 2, 2, 1, 1, 0, 1])

In [281]:
new_train_data = []
for i in range(len(X_train)):
    print(X_train[i])
    print(y_train[i])
    new_train_data.append(np.append(X_train[i], y_train[i]).tolist())
    print(new_train_data)

[5.5 2.3 4.  1.3]
1
[[5.5, 2.3, 4.0, 1.3, 1.0]]
[5.  3.4 1.6 0.4]
0
[[5.5, 2.3, 4.0, 1.3, 1.0], [5.0, 3.4, 1.6, 0.4, 0.0]]
[4.4 3.2 1.3 0.2]
0
[[5.5, 2.3, 4.0, 1.3, 1.0], [5.0, 3.4, 1.6, 0.4, 0.0], [4.4, 3.2, 1.3, 0.2, 0.0]]
[5.6 2.7 4.2 1.3]
1
[[5.5, 2.3, 4.0, 1.3, 1.0], [5.0, 3.4, 1.6, 0.4, 0.0], [4.4, 3.2, 1.3, 0.2, 0.0], [5.6, 2.7, 4.2, 1.3, 1.0]]
[5.7 2.6 3.5 1. ]
1
[[5.5, 2.3, 4.0, 1.3, 1.0], [5.0, 3.4, 1.6, 0.4, 0.0], [4.4, 3.2, 1.3, 0.2, 0.0], [5.6, 2.7, 4.2, 1.3, 1.0], [5.7, 2.6, 3.5, 1.0, 1.0]]
[5.4 3.4 1.5 0.4]
0
[[5.5, 2.3, 4.0, 1.3, 1.0], [5.0, 3.4, 1.6, 0.4, 0.0], [4.4, 3.2, 1.3, 0.2, 0.0], [5.6, 2.7, 4.2, 1.3, 1.0], [5.7, 2.6, 3.5, 1.0, 1.0], [5.4, 3.4, 1.5, 0.4, 0.0]]
[5.2 4.1 1.5 0.1]
0
[[5.5, 2.3, 4.0, 1.3, 1.0], [5.0, 3.4, 1.6, 0.4, 0.0], [4.4, 3.2, 1.3, 0.2, 0.0], [5.6, 2.7, 4.2, 1.3, 1.0], [5.7, 2.6, 3.5, 1.0, 1.0], [5.4, 3.4, 1.5, 0.4, 0.0], [5.2, 4.1, 1.5, 0.1, 0.0]]
[7.4 2.8 6.1 1.9]
2
[[5.5, 2.3, 4.0, 1.3, 1.0], [5.0, 3.4, 1.6, 0.4, 0.0], [4.4, 3.2, 1.3, 0.2, 0

In [282]:
new_test_data = []
for i in range(len(X_test)):
    new_test_data.append(np.append(X_test[i], y_test[i]).tolist())
    print(X_test[i])
    print(y_test[i])
    print(new_test_data)
    

[6.  2.7 5.1 1.6]
1
[[6.0, 2.7, 5.1, 1.6, 1.0]]
[5.9 3.2 4.8 1.8]
1
[[6.0, 2.7, 5.1, 1.6, 1.0], [5.9, 3.2, 4.8, 1.8, 1.0]]
[5.  3.5 1.6 0.6]
0
[[6.0, 2.7, 5.1, 1.6, 1.0], [5.9, 3.2, 4.8, 1.8, 1.0], [5.0, 3.5, 1.6, 0.6, 0.0]]
[5.1 3.8 1.9 0.4]
0
[[6.0, 2.7, 5.1, 1.6, 1.0], [5.9, 3.2, 4.8, 1.8, 1.0], [5.0, 3.5, 1.6, 0.6, 0.0], [5.1, 3.8, 1.9, 0.4, 0.0]]
[5.7 4.4 1.5 0.4]
0
[[6.0, 2.7, 5.1, 1.6, 1.0], [5.9, 3.2, 4.8, 1.8, 1.0], [5.0, 3.5, 1.6, 0.6, 0.0], [5.1, 3.8, 1.9, 0.4, 0.0], [5.7, 4.4, 1.5, 0.4, 0.0]]
[4.4 3.  1.3 0.2]
0
[[6.0, 2.7, 5.1, 1.6, 1.0], [5.9, 3.2, 4.8, 1.8, 1.0], [5.0, 3.5, 1.6, 0.6, 0.0], [5.1, 3.8, 1.9, 0.4, 0.0], [5.7, 4.4, 1.5, 0.4, 0.0], [4.4, 3.0, 1.3, 0.2, 0.0]]
[4.6 3.2 1.4 0.2]
0
[[6.0, 2.7, 5.1, 1.6, 1.0], [5.9, 3.2, 4.8, 1.8, 1.0], [5.0, 3.5, 1.6, 0.6, 0.0], [5.1, 3.8, 1.9, 0.4, 0.0], [5.7, 4.4, 1.5, 0.4, 0.0], [4.4, 3.0, 1.3, 0.2, 0.0], [4.6, 3.2, 1.4, 0.2, 0.0]]
[5.4 3.9 1.7 0.4]
0
[[6.0, 2.7, 5.1, 1.6, 1.0], [5.9, 3.2, 4.8, 1.8, 1.0], [5.0, 3.5, 1.6, 0.6, 0

In [283]:
#Used merge sort for sorting the distances & correspondig dataset
def mergeSort(nlist):
    #print("Splitting ",nlist)
    if len(nlist)>1:
        mid = len(nlist)//2
        lefthalf = nlist[:mid]
        righthalf = nlist[mid:]

        mergeSort(lefthalf)
        mergeSort(righthalf)
        i=j=k=0       
        while i < len(lefthalf) and j < len(righthalf):
            if lefthalf[i][1] < righthalf[j][1]:
                nlist[k]=lefthalf[i]
                i=i+1
            else:
                nlist[k]=righthalf[j]
                j=j+1
            k=k+1

        while i < len(lefthalf):
            nlist[k]=lefthalf[i]
            i=i+1
            k=k+1

        while j < len(righthalf):
            nlist[k]=righthalf[j]
            j=j+1
            k=k+1
            
        
#Finding the Euclidean distanct datapoints/vectors
def distance_Eucl(point1, point2):
    distance = 0.0
    for i in range(len(point1)-1):
        distance =distance + ((point1[i] - point2[i])**2)
    return sqrt(distance)
 
# Find neighbours
def neighbours_search(train_data, rows_test, knn_neighbours):
    distances = list()
    for rows_train in train_data:
        dist = distance_Eucl(rows_test, rows_train)
        distances.append((rows_train, dist))
    mergeSort(distances)    
    neighbors = list()
    for i in range(knn_neighbours):
        neighbors.append(distances[i][0])
    return neighbors
 
# Doing prediction with the neighbours
def classification_pred(train_data, rows_test, knn_neighbours):
    neighbors = neighbours_search(train_data, rows_test, knn_neighbours)
    op_val = [line[-1] for line in neighbors]
    prediction_val = max(set(op_val), key=op_val.count)
    return prediction_val
 
# KNN Algorithm
def KNN_Neighbors(train_data, test, knn_neighbours):
    preds = list()
    for row in test:
        output = classification_pred(train_data, row, knn_neighbours)
        preds.append(output)
#         print(predictions)
    return(preds)


In [284]:
y_pred_data = KNN_Neighbors(new_train_data, new_test_data, 3)
y_pred = []

y_pred = y_pred_data
np.array(y_pred), y_test

# print(len(y_pred) , len(y_test))
# print(y_pred , y_test)
count=0
for i in range(len(y_pred)):
    if y_pred[i]==y_test[i]:
        count=count+1
# print(count)
Acc=count/len(y_pred)
print("Accuracy is :", Acc)
Err_Rate= 1-Acc
print("Error Rate is :",Err_Rate)

Accuracy is : 0.9210526315789473
Error Rate is : 0.07894736842105265


# KNN ALgorithm for IONOSPHERE_DATASET(General K value(Commented) & 1-NN (using genfromtxt function)

In [285]:
"""
Implemented the K Nearest Neighbours algorithm for a general K but used 1 & 3 instead of K in the programs
 
"""

from random import seed
from random import randrange
from math import sqrt
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
import numpy as np
ion_data = np.genfromtxt("ionosphere.txt", delimiter=",")

In [286]:
# print(ion_data)
# print(len(ion_data))
# len(ion_data[-1])
# x = ion_data[:, 0]
x = ion_data[:, :-1]
print(x[0])
print(x.shape)
y = ion_data[:, -1]
print(y.shape)

[ 1.       0.       0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708
  1.       0.0376   0.85243 -0.17755  0.59755 -0.44945  0.60536 -0.38223
  0.84356 -0.38542  0.58212 -0.32192  0.56971 -0.29674  0.36946 -0.47357
  0.56811 -0.51171  0.41078 -0.46168  0.21266 -0.3409   0.42267 -0.54487
  0.18641 -0.453  ]
(351, 34)
(351,)


In [287]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=705)

In [288]:
# print(X_train, X_test, y_train, y_test)
print(X_train)
print(X_train.shape)

[[ 1.0000e+00  0.0000e+00  1.0000e+00 ... -3.2540e-01 -1.0000e+00
   7.2831e-01]
 [ 1.0000e+00  0.0000e+00  3.9179e-01 ...  1.3521e-01  3.4411e-01
   1.2755e-01]
 [ 1.0000e+00  0.0000e+00  0.0000e+00 ...  1.1778e-01  9.0667e-01
  -9.5560e-02]
 ...
 [ 1.0000e+00  0.0000e+00  8.7032e-01 ...  5.6573e-01 -6.7390e-02
   5.7552e-01]
 [ 1.0000e+00  0.0000e+00  0.0000e+00 ...  0.0000e+00  0.0000e+00
   0.0000e+00]
 [ 1.0000e+00  0.0000e+00  2.5000e-01 ... -4.0800e-03  2.5000e-04
  -2.9100e-03]]
(263, 34)


In [289]:
new_train_data = []
for i in range(len(X_train)):
    new_train_data.append(np.append(X_train[i], y_train[i]).tolist())
print(new_train_data[262])
print(len(new_train_data))

[1.0, 0.0, 0.25, 0.16667, 0.46667, 0.26667, 0.19036, 0.23966, 0.07766, 0.19939, 0.0107, 0.14922, -0.02367, 0.10188, -0.03685, 0.06317, -0.03766, 0.03458, -0.0323, 0.01532, -0.02474, 0.00357, -0.01726, -0.00273, -0.01097, -0.00539, -0.00621, -0.00586, -0.00294, -0.0052, -0.00089, -0.00408, 0.00025, -0.00291, 1.0]
263


In [290]:
new_test_data = []
for i in range(len(X_test)):
    new_test_data.append(np.append(X_test[i], y_test[i]).tolist())
print(new_test_data[87])

[1.0, 0.0, 1.0, 1.0, 1.0, 0.5125, 0.625, -1.0, 1.0, 1.0, 0.025, 0.03125, 1.0, 1.0, 0.0, 0.0, 1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 0.3125, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -0.94375, 1.0, 0.0, 0.0, -1.0]


In [291]:

def mergeSort(nlist):
    #print("Splitting ",nlist)
    if len(nlist)>1:
        mid = len(nlist)//2
        lefthalf = nlist[:mid]
        righthalf = nlist[mid:]

        mergeSort(lefthalf)
        mergeSort(righthalf)
        i=j=k=0       
        while i < len(lefthalf) and j < len(righthalf):
            if lefthalf[i][1] < righthalf[j][1]:
                nlist[k]=lefthalf[i]
                i=i+1
            else:
                nlist[k]=righthalf[j]
                j=j+1
            k=k+1

        while i < len(lefthalf):
            nlist[k]=lefthalf[i]
            i=i+1
            k=k+1

        while j < len(righthalf):
            nlist[k]=righthalf[j]
            j=j+1
            k=k+1
            
        
#Finding the Euclidean distanct datapoints/vectors
def distance_Eucl(point1, point2):
    distance = 0.0
    for i in range(len(point1)-1):
        distance =distance + ((point1[i] - point2[i])**2)
    return sqrt(distance)
 
# Find neighbours
def neighbours_search(train_data, rows_test, knn_neighbours):
    distances = list()
    for rows_train in train_data:
        dist = distance_Eucl(rows_test, rows_train)
        distances.append((rows_train, dist))
    mergeSort(distances)    
    neighbors = list()
    for i in range(knn_neighbours):
        neighbors.append(distances[i][0])
    return neighbors
 
# Doing prediction with the neighbours
def classification_pred(train_data, rows_test, knn_neighbours):
    neighbors = neighbours_search(train_data, rows_test, knn_neighbours)
    op_val = [line[-1] for line in neighbors]
    prediction_val = max(set(op_val), key=op_val.count)
    return prediction_val
 
# KNN Algorithm
def KNN_Neighbors(train_data, test, knn_neighbours):
    preds = list()
    for row in test:
        output = classification_pred(train_data, row, knn_neighbours)
        preds.append(output)
#         print(predictions)
    return(preds)

In [292]:
#for genralized k value we can use the below commented function:
# k=int(input("enter the k value of KNN"))
# y_pred_data = KNN_Neighbors(new_train_data, new_test_data, k)
y_pred_data = KNN_Neighbors(new_train_data, new_test_data, 1)
y_pred = []

y_pred = y_pred_data
np.array(y_pred), y_test

print(len(y_pred) , len(y_test))
print(y_pred , y_test)
count=0
for i in range(len(y_pred)):
    if y_pred[i]==y_test[i]:
        count=count+1
# print(count)
Acc=count/len(y_pred)
print("Accuracy is",Acc)
Err_Rate= 1-Acc
print("Error Rate is",Err_Rate)

88 88
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, -1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, -1.0, -1.0, 1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0] [ 1. -1.  1.  1.  1.  1. -1.  1. -1.  1. -1.  1.  1. -1.  1. -1. -1. -1.
  1. -1.  1. -1. -1.  1.  1.  1.  1. -1.  1.  1.  1.  1. -1.  1.  1.  1.
  1.  1.  1. -1.  1.  1.  1.  1.  1.  1.  1.  1. -1.  1. -1. -1.  1. -1.
  1. -1. -1.  1.  1. -1.  1. -1.  1.  1. -1. -1.  1.  1.  1.  1. -1. -1.
  1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1.  1.  1.  1. -1.]
Accuracy is 0.8636363636363636
Error Rate is 0.13636363636363635


# IONOSPHERE_Dataset & 3-NN Algorithm (using genfromtxt function)

In [293]:
"""
Implemented the K Nearest Neighbours algorithm for a general K but used 1 & 3 instead of K in the programs
 
"""

from random import seed
from random import randrange
from math import sqrt
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
import numpy as np
ion_data = np.genfromtxt("ionosphere.txt", delimiter=",")

In [294]:
x = ion_data[:, :-1]
print(x.shape)
y = ion_data[:, -1]
print(y.shape)

(351, 34)
(351,)


In [295]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=705)
print(X_train)
print(X_train.shape)

[[ 1.0000e+00  0.0000e+00  1.0000e+00 ... -3.2540e-01 -1.0000e+00
   7.2831e-01]
 [ 1.0000e+00  0.0000e+00  3.9179e-01 ...  1.3521e-01  3.4411e-01
   1.2755e-01]
 [ 1.0000e+00  0.0000e+00  0.0000e+00 ...  1.1778e-01  9.0667e-01
  -9.5560e-02]
 ...
 [ 1.0000e+00  0.0000e+00  8.7032e-01 ...  5.6573e-01 -6.7390e-02
   5.7552e-01]
 [ 1.0000e+00  0.0000e+00  0.0000e+00 ...  0.0000e+00  0.0000e+00
   0.0000e+00]
 [ 1.0000e+00  0.0000e+00  2.5000e-01 ... -4.0800e-03  2.5000e-04
  -2.9100e-03]]
(263, 34)


In [296]:
new_train_data = []
for i in range(len(X_train)):
    new_train_data.append(np.append(X_train[i], y_train[i]).tolist())
print(new_train_data[262])
print(len(new_train_data))

[1.0, 0.0, 0.25, 0.16667, 0.46667, 0.26667, 0.19036, 0.23966, 0.07766, 0.19939, 0.0107, 0.14922, -0.02367, 0.10188, -0.03685, 0.06317, -0.03766, 0.03458, -0.0323, 0.01532, -0.02474, 0.00357, -0.01726, -0.00273, -0.01097, -0.00539, -0.00621, -0.00586, -0.00294, -0.0052, -0.00089, -0.00408, 0.00025, -0.00291, 1.0]
263


In [297]:
new_test_data = []
for i in range(len(X_test)):
    new_test_data.append(np.append(X_test[i], y_test[i]).tolist())
print(new_test_data[87])

[1.0, 0.0, 1.0, 1.0, 1.0, 0.5125, 0.625, -1.0, 1.0, 1.0, 0.025, 0.03125, 1.0, 1.0, 0.0, 0.0, 1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 0.3125, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -0.94375, 1.0, 0.0, 0.0, -1.0]


In [298]:
def mergeSort(nlist):
    #print("Splitting ",nlist)
    if len(nlist)>1:
        mid = len(nlist)//2
        lefthalf = nlist[:mid]
        righthalf = nlist[mid:]

        mergeSort(lefthalf)
        mergeSort(righthalf)
        i=j=k=0       
        while i < len(lefthalf) and j < len(righthalf):
            if lefthalf[i][1] < righthalf[j][1]:
                nlist[k]=lefthalf[i]
                i=i+1
            else:
                nlist[k]=righthalf[j]
                j=j+1
            k=k+1

        while i < len(lefthalf):
            nlist[k]=lefthalf[i]
            i=i+1
            k=k+1

        while j < len(righthalf):
            nlist[k]=righthalf[j]
            j=j+1
            k=k+1
            
        
#Finding the Euclidean distanct datapoints/vectors
def distance_Eucl(point1, point2):
    distance = 0.0
    for i in range(len(point1)-1):
        distance =distance + ((point1[i] - point2[i])**2)
    return sqrt(distance)
 
# Find neighbours
def neighbours_search(train_data, rows_test, knn_neighbours):
    distances = list()
    for rows_train in train_data:
        dist = distance_Eucl(rows_test, rows_train)
        distances.append((rows_train, dist))
    mergeSort(distances)    
    neighbors = list()
    for i in range(knn_neighbours):
        neighbors.append(distances[i][0])
    return neighbors
 
# Doing prediction with the neighbours
def classification_pred(train_data, rows_test, knn_neighbours):
    neighbors = neighbours_search(train_data, rows_test, knn_neighbours)
    op_val = [line[-1] for line in neighbors]
    prediction_val = max(set(op_val), key=op_val.count)
    return prediction_val
 
# KNN Algorithm
def KNN_Neighbors(train_data, test, knn_neighbours):
    preds = list()
    for row in test:
        output = classification_pred(train_data, row, knn_neighbours)
        preds.append(output)
#         print(predictions)
    return(preds)

In [299]:
y_pred_data = KNN_Neighbors(new_train_data, new_test_data, 3)
y_pred = []

y_pred = y_pred_data
np.array(y_pred), y_test

print(len(y_pred) , len(y_test))
print(y_pred , y_test)
count=0
for i in range(len(y_pred)):
    if y_pred[i]==y_test[i]:
        count=count+1
print(count)
Acc=count/len(y_pred)
print("Accuracy is",Acc)
Err_Rate= 1-Acc
print("Error Rate is",Err_Rate)

88 88
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, -1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, -1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0] [ 1. -1.  1.  1.  1.  1. -1.  1. -1.  1. -1.  1.  1. -1.  1. -1. -1. -1.
  1. -1.  1. -1. -1.  1.  1.  1.  1. -1.  1.  1.  1.  1. -1.  1.  1.  1.
  1.  1.  1. -1.  1.  1.  1.  1.  1.  1.  1.  1. -1.  1. -1. -1.  1. -1.
  1. -1. -1.  1.  1. -1.  1. -1.  1.  1. -1. -1.  1.  1.  1.  1. -1. -1.
  1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1.  1.  1.  1. -1.]
75
Accuracy is 0.8522727272727273
Error Rate is 0.1477272727272727
